function R = Ramsey_ss(x, eta, rho, kappa, delta,...
            g, L)

 R = [(x(1)./eta).*((L^(1-kappa)*kappa)*x(2).^(kappa-1)-rho-(delta+g));... 
       x(2).^(kappa)*L^(1-kappa)-x(1)+(delta+g)*x(1)];